# Generated by Django 5.0.1 on 2024-01-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stop_Times',
            fields=[
                ('serial', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trip_identifier', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_identifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stop_code', models.CharField(max_length=100)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_lat', models.FloatField()),
                ('stop_long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('route_id', models.CharField(max_length=50)),
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(max_length=200)),
            ],
        ),
    ]
