# Generated by Django 5.0.1 on 2024-01-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop_times',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
